# Generated by Django 4.1.3 on 2023-06-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('tipo_medico', models.CharField(choices=[('1', 'Medicina General'), ('2', 'Odontologia'), ('3', 'Pediatria'), ('4', 'Nutricionista'), ('5', 'Ginecologia')], max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
