# Generated by Django 4.1.3 on 2023-06-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medico_delete_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('nombre_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medico')),
            ],
        ),
    ]
