# Generated by Django 4.1.3 on 2023-06-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='tipo_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipomedico'),
        ),
    ]
